# Generated by Django 5.1.6 on 2025-03-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('mdp', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
