# Generated by Django 5.1.6 on 2025-03-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('idcommentaire', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'commentaire',
                'managed': False,
            },
        ),
    ]
