# Generated by Django 5.1.6 on 2025-03-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('idachat', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'achat',
                'managed': False,
            },
        ),
    ]
